name: cargo build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build debug
      run: cargo build --verbose
    - name: Run tests on debug
      run: cargo test --verbose
    - name: run integration testing
      run: ./test/debug.sh
    - name: JUnit Report Action
      uses: mikepenz/action-junit-report@v3.7.1
      with:
        report_paths: '***/report.xml'
